### ISSUE TITLE
Authentication.json

### ISSUE THREAD

**Issue by oxodi** [muffycompo/radiusdesk-installer#51]
Hi,
I have an issue on this file, from web during the login i see an error "Ajax comunication failed", and in debug option from browser i see error 500 on file Authentication.json.
Anyone know how to fix this issue?

**Comment by alxAgu** [comment]
I've got the same issue. Did you manage to fix it @oxodi?

**Comment by phillyint** [comment]
Hi All!

I've been working on this issue for a few days now and I think I've gotten it to the point where I need a bit of help. I've cloned RadiusDesk Installer to my EC2 instance of and then I updated it from this link: http://www.radiusdesk.com/docuwiki/getting_started/install_ubuntu_update

In Chrome, it indicates: "Failed to load resource: the server responded with a status of 404 (Not Found)" in the console and when I check the /usr/share/nginx/html/cake3/rd_cake directory, I don't see anything in /cake3/rd_cake -> there is no /dashboard/ folder and consequently, there is no authenticate.json file. Not sure if this is a sign of a larger issue or not.

Also, I checked in cake2 and I don't see the folder/file there either, so it would seem to me that something may have prevented this in the build. With that in mind, I've been thinking that this is a "missed package update" or some other step that was prevented due to permissions or something like that. I have a local VMware instance that is running fine. I could try to use the image, but I would prefer to get the build done with the script.

Any thoughts?

Regards,
James

**Comment by alxAgu** [comment]
@phillyint, I eventually gave up on installing this on Ubuntu 16 and after switching to 14.04.5 the installation went flawlessly.

**Comment by oxodi** [comment]
Solved with manual and fresh install. 
But now i'm try to configure social login, but Thanks to Facebook, i need an https request, accordingly the new stricht uri mode. 
I install an ssl certificate on radiusdesk but, of course, it don't work. 
It say hotspot not responding.

**Comment by muffycompo** [comment]
There is a thread on this issue #7. Kindly follow that and see if it resolves the issue you are having.

**Comment by muffycompo** [comment]
Issue resolved in #7 . Closing this thread.
